name: Run tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -e ./backend

      - name: Run tests with coverage
        run: |
          pytest --cov=core --cov-report=term-missing

      - name: Build Docker image
        run: |
          docker build -t quantsim-test backend/Dockerfile .


